#!/bin/sh
# This script should be in /etc/initramfs-tools/hooks

PREREQ=""

prereqs()
{
	echo "$PREREQ"
}

case $1 in
	prereqs) echo "${PREREQS}"; exit 0;;
esac

. /usr/share/initramfs-tools/hook-functions

copy_exec /sbin/jindisksetup


